apiVersion: v1
kind: Pod
metadata:
  name: affinity-pod-2
  labels:
    env: demo
spec:
  containers:
  - name: container2
    image: nginx:latest
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1
        preference:
          matchExpressions:
          - key: env
            operator: In
            values:
            - demo

# Operators include In, NotIn, Exists, DoesNotExist, Gt and Lt.
# NotIn and DoesNotExist allow you to define node anti-affinity behavior.
# two types of nodeAffinity - 
# 1. requireDuringSchedulingIngnoredDuringExecution
# 2. preferredDuringSchedulingIgnoredDuringExecution
# IgnoredDuringExecution implies that pods that are already scheduled in the node will not be evicted if there is any change in the label to the node.
# If there are more affinity rules with preferredDuringSchedulingIgnoredDuringExecution type then the one with more weight will be scheduled first.
