apiVersion: v1
kind: Pod
metadata:
  name: samplepod
  labels:
    app: sampleapp
spec:
  containers:
  - name: samplecontainer
    image: nginx:latest
    ports:
    - containerPort: 80
      protocol: TCP   
  tolerations:
  - key: "env"
    operator: "Equal"
    value: "demo"
    effect: "NoSchedule"

#Taints are applied on node.
#Tolerations are applied on pods.
#kubectl taint node <nodename> <key>=<value>:NoSchedule/NoExecute/PreferNoSchedule --> to taint a node
#kubectl taint node <nodename> <key>=<value>:NoSchedule/NoExecute/PreferNoSchedule- --> put - at the end effect to untaint

#NoSchedule --> on new pods
#NoExecute --> on new and existinf pods on node
#PreferNoSchedule --> same as NoSchedule but no guarantee