apiVersion: v1
kind: Service
metadata:
  name: clusterip-svc
spec:
  type: ClusterIP
  selector:
    app: appname
  ports:
  - targetPort: 80
    protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: nodeport-svc
spec:
  type: NodePort
  selector:
    app: appname
  ports:
  - targetPort: 80
    port: 80
    nodePort: 30001
    protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: loadbalancer-svc
spec:
  type: LoadBalancer
  selector:
    app: appname
  ports:
  - targetPort: 80
    protocol: TCP